### ISSUE TITLE
Doing this project without the LCD code

### ISSUE THREAD

**Issue by shoaibsajid1** [cchannon/WhatIsThis#1]
Hi I want to create this exact project and i am not a programmer. I want to use the .py code minus the adafruit LCD part and show the results in the terminal or message box itself. Thanks so much if you can help me do that <3

**Comment by cchannon** [comment]
What kind of a display are you planning to use? Are you thinking about just having a monitor up and just watching the Py script scroll by in console?

**Comment by cchannon** [comment]
Also, this code is pretty old; the API call I used probably needs updating by now...
